name: Android CI

on:
  push:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Publish with Gradle
      env:
        IS_CICD: $IS_CICD
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      run: ./gradlew artifactoryPublish
